import { expect,it } from "vitest";
import { reminderCandidates,reminderVisible,DAY } from "@/modules/reminders/rules";
import { exitSchema,type ExitRecord } from "@/modules/exits/shared";
import { buildChecklist } from "@/modules/exits/rules";
import { retryDelay,validJob } from "@/server/jobs/queue";
const now=new Date('2026-10-10T00:00:00Z');
function exit():ExitRecord {const answers=exitSchema.parse({exitType:'resignation',lastWorkingDate:'2026-10-31'});return {id:'case',employmentId:'job',employerName:'private',roleTitle:'worker',version:0,createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',answers,rulesVersion:'v1',checklist:buildChecklist(answers,{employmentStart:'2024-01-01',documents:[],noticeFields:[]})};}
it('derives missing-document and exit-action prompts only for unresolved rules',()=>{const result=reminderCandidates(exit(),null,now);expect(result.find(i=>i.key==='exit_documents')?.kind).toBe('missing_document');expect(result.find(i=>i.key==='notice')?.kind).toBe('exit_action');expect(result.find(i=>i.key==='stale_action')?.kind).toBe('stale_action');expect(JSON.stringify(result)).not.toContain('private');});
it('suppresses complete/not applicable actions and stale checks before seven days',()=>{const record=exit();record.checklist=record.checklist.map(item=>({...item,state:'complete'}));expect(reminderCandidates(record,null,now)).toEqual([]);record.checklist=buildChecklist(record.answers,{employmentStart:'2024-01-01',documents:[],noticeFields:[]});expect(reminderCandidates(record,null,new Date('2026-10-07T23:59:59Z')).some(i=>i.kind==='stale_action')).toBe(false);expect(reminderCandidates(record,null,new Date('2026-10-08T00:00:00Z')).some(i=>i.kind==='stale_action')).toBe(true);});
it('uses saved pension follow-up only while participating and unconfirmed',()=>{const record=exit();record.answers.pension='yes';const pension={id:'p',version:0,targetPeriod:'2026-10',statementRunId:null,expectedFieldId:null,expectedFieldVersion:null,followUpDate:'2026-11-30',confirmedAt:null,evidenceToken:'token',result:{state:'waiting',message:'',nextAction:''}};expect(reminderCandidates(record,pension,now).find(i=>i.kind==='pension_followup')?.dueAt.toISOString()).toBe('2026-11-30T00:00:00.000Z');for(const change of [{followUpDate:null},{result:{...pension.result,state:'confirmed'}}])expect(reminderCandidates(record,{...pension,...change},now).some(i=>i.kind==='pension_followup')).toBe(false);record.answers.pension='no';expect(reminderCandidates(record,pension,now).some(i=>i.kind==='pension_followup')).toBe(false);});
it('keeps stable fingerprints, respects snooze/dismiss and wakes changed issues',()=>{const candidate=reminderCandidates(exit(),null,now)[0]!;expect(candidate.fingerprint).toBe(reminderCandidates(exit(),null,now)[0]!.fingerprint);expect(reminderVisible({state:'dismissed',fingerprint:candidate.fingerprint,snoozedUntil:null},candidate,now)).toBe(false);expect(reminderVisible({state:'dismissed',fingerprint:'old',snoozedUntil:null},candidate,now)).toBe(true);const row={state:'snoozed',fingerprint:candidate.fingerprint,snoozedUntil:new Date(now.getTime()+DAY)};expect(reminderVisible(row,candidate,now)).toBe(false);expect(reminderVisible(row,candidate,row.snoozedUntil)).toBe(true);expect(reminderVisible({...row,state:'active'}, {...candidate,dueAt:new Date(now.getTime()+DAY)},now)).toBe(false);});
it('bounds retry delays and restricts job kinds',()=>{expect(retryDelay(0)).toBe(10000);expect(retryDelay(3)).toBe(80000);expect(retryDelay(100)).toBe(1800000);expect(validJob('session_cleanup')).toBe(true);expect(validJob('execute-arbitrary-code')).toBe(false);});
